### PR TITLE
feat(table): pagination rows and zebra feature

### PR DESCRIPTION
**Pull request by theJohnnyMe**
Adding examples on Table component:

- zebra rows and columns
- rows per page logic

### CODE REVIEW

**Review by nathalielindqvist — COMMENTED** [review]
When setting rows per page to 2, navigating all the way back to the last page and then setting the rows per page to 6 the Table still displays it as page 4, but only having 2 pages total and showing no data. Is this intended behavior?
Screenshot 2024-10-04 at 09 46 30

**Review by nathalielindqvist — COMMENTED** [review]
When hovering one Table header cell to get the hover effect on the column, all corresponding columns in all other Tables gets the hover effect too. This is across all Tegel Tables, not just the newly introduced zebra ones. However, the pagination example of the Table do not get the hover effect on the columns at all. Not sure it has something to do with lack of table ids or if it's something else? This issue does not exist in the regular Angular demo page

**Comment by Lunkan89** [comment]
> When setting rows per page to 2, navigating all the way back to the last page and then setting the rows per page to 6 the Table still displays it as page 4, but only having 2 pages total and showing no data. Is this intended behavior? Screenshot 2024-10-04 at 09 46 30

Great eye @nathalielindqvist
huston we have a bugg.

**Comment by theJohnnyMe** [comment]
The new Tegel release has fixed the issue with pagination.

**Pull request merged**
